# Generated by Django 2.1.5 on 2020-05-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200528_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
